# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"9\n\x0ePaymentRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\"F\n\x0fPaymentResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x03 \x01(\t2T\n\x0ePaymentService\x12\x42\n\rCreatePayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTREQUEST']._serialized_start=26
  _globals['_PAYMENTREQUEST']._serialized_end=83
  _globals['_PAYMENTRESPONSE']._serialized_start=85
  _globals['_PAYMENTRESPONSE']._serialized_end=155
  _globals['_PAYMENTSERVICE']._serialized_start=157
  _globals['_PAYMENTSERVICE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
